"""role_add_info

Revision ID: e13a5191bc38
Revises: 0e4f4eae25c3
Create Date: 2018-03-27 12:16:33.785653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13a5191bc38'
down_revision = '0e4f4eae25c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('info', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'info')
    # ### end Alembic commands ###
